stages:
  - install
  - build
  - test
  - deploy

variables:
  FRONTEND_DIR: homework-frontend
  BACKEND_DIR: homework-backend

install-frontend:
  stage: install
  image: node:20
  script:
    - cd $FRONTEND_DIR
    - npm ci
  artifacts:
    paths:
      - $FRONTEND_DIR/node_modules

install-backend:
  stage: install
  image: node:20
  script:
    - cd $BACKEND_DIR
    - npm ci
  artifacts:
    paths:
      - $BACKEND_DIR/node_modules

build-frontend:
  stage: build
  image: node:20
  dependencies:
    - install-frontend
  script:
    - cd $FRONTEND_DIR
    - npm run build
  artifacts:
    paths:
      - $FRONTEND_DIR/dist

build-backend:
  stage: build
  image: node:20
  dependencies:
    - install-backend
  script:
    - cd $BACKEND_DIR
    - npm run build
  artifacts:
    paths:
      - $BACKEND_DIR/dist

test-frontend:
  stage: test
  image: node:20
  dependencies:
    - install-frontend
  script:
    - cd $FRONTEND_DIR
    - npm run test

test-backend:
  stage: test
  image: node:20
  dependencies:
    - install-backend
  script:
    - cd $BACKEND_DIR
    - npm run test

pages:
  stage: deploy
  image: node:20
  dependencies:
    - build-frontend
  script:
    - mkdir -p public
    - cp -r $FRONTEND_DIR/dist/* public/
  artifacts:
    paths:
      - public